steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/customer-service', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'customer-service',
         '--image', 'gcr.io/$PROJECT_ID/customer-service',
         '--platform', 'managed',
         '--region', 'us-central1']